<a href="https://colab.research.google.com/github/Adi7171/scraping/blob/main/QsRanking%20scrap/QS_ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install selenium
!apt-get update 
!apt install chromium-chromedriver

Collecting selenium
  Downloading selenium-4.1.0-py3-none-any.whl (958 kB)
     |████████████████████████████████| 958 kB 4.9 MB/s
Collecting urllib3[secure]~=1.26
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 60.8 MB/s
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Collecting trio~=0.17
  Downloading trio-0.19.0-py3-none-any.whl (356 kB)
     |████████████████████████████████| 356 kB 53.2 MB/s
Collecting outcome
  Downloading outcome-1.1.0-py2.py3-none-any.whl (9.7 kB)
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (2.10)
Collecting async-generator>=1.9
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.7/dist-packages (from trio~=0.17->selenium) (21.4.0)
Collecting wsproto>=0.14
  Downloading wsproto-1.0.0-py3-none-any.whl (24 kB)
Collecting pyOpenSSL>=0.14
  Downloading pyOpenSSL-22.0.0-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.3 MB/s
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from urllib3[secure]~=1.26->selenium) (2021.10.8)
Collecting cryptography>=1.3.4
  Downloading cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 52.8 MB/s
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=1.3.4->urllib3[secure]~=1.26->selenium) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=1.3.4->urllib3[secure]~=1.26->selenium) (2.21)
Collecting h11<1,>=0.9.0
  Downloading h11-0.13.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.4 MB/s
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from h11<1,>=0.9.0->wsproto>=0.14->trio-websocket~=0.9->selenium) (3.10.0.2)
Installing collected packages: sniffio, outcome, h11, cryptography, async-generator, wsproto, urllib3, trio, pyOpenSSL, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.23.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you have urllib3 1.26.8 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed async-generator-1.10 cryptography-36.0.1 h11-0.13.0 outcome-1.1.0 pyOpenSSL-22.0.0 selenium-4.1.0 sniffio-1.2.0 trio-0.19.0 trio-websocket-0.9.2 urllib3-1.26.8 wsproto-1.0.0

Get:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:11 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:13 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:14 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease [21.3 kB]
Get:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [917 kB]
Get:17 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main Sources [1,825 kB]
Get:18 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [21.1 kB]
Get:19 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [783 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,247 kB]
Get:21 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,468 kB]
Get:22 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,564 kB]
Get:23 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic/main amd64 Packages [935 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [816 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.0 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3,004 kB]
Get:27 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic/main amd64 Packages [42.8 kB]
Fetched 14.9 MB in 4s (3,951 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cuda-command-line-tools-10-0 cuda-command-line-tools-10-1
  cuda-command-line-tools-11-0 cuda-compiler-10-0 cuda-compiler-10-1
  cuda-compiler-11-0 cuda-cuobjdump-10-0 cuda-cuobjdump-10-1
  cuda-cuobjdump-11-0 cuda-cupti-10-0 cuda-cupti-10-1 cuda-cupti-11-0
  cuda-cupti-dev-11-0 cuda-documentation-10-0 cuda-documentation-10-1
  cuda-documentation-11-0 cuda-documentation-11-1 cuda-gdb-10-0 cuda-gdb-10-1
  cuda-gdb-11-0 cuda-gpu-library-advisor-10-0 cuda-gpu-library-advisor-10-1
  cuda-libraries-10-0 cuda-libraries-10-1 cuda-libraries-11-0
  cuda-memcheck-10-0 cuda-memcheck-10-1 cuda-memcheck-11-0 cuda-nsight-10-0
  cuda-nsight-10-1 cuda-nsight-11-0 cuda-nsight-11-1 cuda-nsight-compute-10-0
  cuda-nsight-compute-10-1 cuda-nsight-compute-11-0 cuda-nsight-compute-11-1
  cuda-nsight-systems-10-1 cuda-nsight-systems-11-0 cuda-nsight-systems-11-1
  cuda-nvcc-10-0 cuda-nvcc-10-1 cuda-nvcc-11-0 cuda-nvdisasm-10-0
  cuda-nvdisasm-10-1 cuda-nvdisasm-11-0 cuda-nvml-dev-10-0 cuda-nvml-dev-10-1
  cuda-nvml-dev-11-0 cuda-nvprof-10-0 cuda-nvprof-10-1 cuda-nvprof-11-0
  cuda-nvprune-10-0 cuda-nvprune-10-1 cuda-nvprune-11-0 cuda-nvtx-10-0
  cuda-nvtx-10-1 cuda-nvtx-11-0 cuda-nvvp-10-0 cuda-nvvp-10-1 cuda-nvvp-11-0
  cuda-nvvp-11-1 cuda-samples-10-0 cuda-samples-10-1 cuda-samples-11-0
  cuda-samples-11-1 cuda-sanitizer-11-0 cuda-sanitizer-api-10-1
  cuda-toolkit-10-0 cuda-toolkit-10-1 cuda-toolkit-11-0 cuda-toolkit-11-1
  cuda-tools-10-0 cuda-tools-10-1 cuda-tools-11-0 cuda-tools-11-1
  cuda-visual-tools-10-0 cuda-visual-tools-10-1 cuda-visual-tools-11-0
  cuda-visual-tools-11-1 default-jre dkms freeglut3 freeglut3-dev
  keyboard-configuration libargon2-0 libcap2 libcryptsetup12
  libdevmapper1.02.1 libfontenc1 libidn11 libip4tc0 libjansson4
  libnvidia-cfg1-510 libnvidia-common-460 libnvidia-common-510
  libnvidia-extra-510 libnvidia-fbc1-510 libnvidia-gl-510 libpam-systemd
  libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0 libxfont2
  libxi-dev libxkbfile1 libxmu-dev libxmu-headers libxnvctrl0
  nsight-compute-2020.2.1 nsight-compute-2022.1.0 nsight-systems-2020.3.2
  nsight-systems-2020.3.4 nsight-systems-2021.5.2 nvidia-dkms-510
  nvidia-kernel-common-510 nvidia-kernel-source-510 nvidia-modprobe
  nvidia-settings openjdk-11-jre policykit-1 policykit-1-gnome python3-xkit
  screen-resolution-extra systemd systemd-sysv udev x11-xkb-utils
  xserver-common xserver-xorg-core-hwe-18.04 xserver-xorg-video-nvidia-510
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra
Suggested packages:
  webaccounts-chromium-extension unity-chromium-extension
The following NEW packages will be installed:
  chromium-browser chromium-browser-l10n chromium-chromedriver
  chromium-codecs-ffmpeg-extra
0 upgraded, 4 newly installed, 0 to remove and 63 not upgraded.
Need to get 95.3 MB of archives.
After this operation, 327 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-codecs-ffmpeg-extra amd64 97.0.4692.71-0ubuntu0.18.04.1 [1,142 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-browser amd64 97.0.4692.71-0ubuntu0.18.04.1 [84.7 MB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-browser-l10n all 97.0.4692.71-0ubuntu0.18.04.1 [4,370 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 chromium-chromedriver amd64 97.0.4692.71-0ubuntu0.18.04.1 [5,055 kB]
Fetched 95.3 MB in 4s (23.7 MB/s)
Selecting previously unselected package chromium-codecs-ffmpeg-extra.
(Reading database ... 155113 files and directories currently installed.)
Preparing to unpack .../chromium-codecs-ffmpeg-extra_97.0.4692.71-0ubuntu0.18.04.1_amd64.deb ...
Unpacking chromium-codecs-ffmpeg-extra (97.0.4692.71-0ubuntu0.18.04.1) ...
Selecting previously unselected package chromium-browser.
Preparing to unpack .../chromium-browser_97.0.4692.71-0ubuntu0.18.04.1_amd64.deb ...
Unpacking chromium-browser (97.0.4692.71-0ubuntu0.18.04.1) ...
Selecting previously unselected package chromium-browser-l10n.
Preparing to unpack .../chromium-browser-l10n_97.0.4692.71-0ubuntu0.18.04.1_all.deb ...
Unpacking chromium-browser-l10n (97.0.4692.71-0ubuntu0.18.04.1) ...
Selecting previously unselected package chromium-chromedriver.
Preparing to unpack .../chromium-chromedriver_97.0.4692.71-0ubuntu0.18.04.1_amd64.deb ...
Unpacking chromium-chromedriver (97.0.4692.71-0ubuntu0.18.04.1) ...
Setting up chromium-codecs-ffmpeg-extra (97.0.4692.71-0ubuntu0.18.04.1) ...
Setting up chromium-browser (97.0.4692.71-0ubuntu0.18.04.1) ...
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
Setting up chromium-chromedriver (97.0.4692.71-0ubuntu0.18.04.1) ...
Setting up chromium-browser-l10n (97.0.4692.71-0ubuntu0.18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link

In [ ]:
!pip install bs4

Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4) (4.6.3)

In [ ]:
from selenium import webdriver
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: use options instead of chrome_options

In [ ]:
import time
from bs4 import BeautifulSoup

In [ ]:

driver.get('https://www.topuniversities.com/university-rankings/world-university-rankings/2022')
time.sleep(4)
html = driver.page_source
soup = BeautifulSoup(html,'html.parser')
# print(soup)

In [ ]:

data = []
sc=[]
for j in range(100):
  time.sleep(2)
  html = driver.page_source
  soup = BeautifulSoup(html,'html.parser')
  time.sleep(4)
  # select = driver.find_element_by_xpath ('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]')
  # select = driver.find_element_by_xpath ('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]')
  # select.click()
  # x = driver.find_element_by_xpath('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]/div[2]/div[4]')
  # x.click()
  # html = driver.page_source
  # soup = BeautifulSoup(html,'html.parser')
  # txt = driver.find_element_by_xpath('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]/div[1]')
  # time.sleep(4)
  uni = soup.find_all( class_ = "uni-link" )
  score = soup.find_all( class_ = "overall-score-span" )
  
  count_no= driver.find_element_by_css_selector('#_outoftotalcounts')
 
  print("counts ",count_no.text)
  for i in range(10):
    print("inside loop",j)
    data.append(uni[i].text)
    sc.append(score[i].text)


   

  next_pg = driver.find_element_by_css_selector('.next')
  next_pg.click()

In [ ]:
# html = driver.page_source
# soup = BeautifulSoup(html,'html.parser')
# time.sleep(4)
# select = driver.find_element_by_xpath ('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]')
# driver.maximize_window()
# drop= driver.find_element_by_xpath('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]/div[1]')
# drop.click()
# x = driver.find_element_by_xpath('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]/div[2]/div[4]')
# x.click()
# html = driver.page_source
# soup = BeautifulSoup(html,'html.parser')
# txt = driver.find_element_by_xpath('//*[@id="block-tu-d8-content"]/div/article/div/div[3]/div/div[1]/div/div[3]/div[4]/div[1]/div[2]/div[1]')
# print(txt)

In [ ]:
sc

In [ ]:
data

['Massachusetts Institute of Technology (MIT) ',
 'University of Oxford',
 'Stanford University',
 'University of Cambridge',
 'Harvard University',
 'California Institute of Technology (Caltech)',
 'Imperial College London',
 'ETH Zurich - Swiss Federal Institute of Technology',
 'UCL',
 'University of Chicago',
 'National University of Singapore (NUS)',
 'Nanyang Technological University, Singapore (NTU)',
 'University of Pennsylvania',
 'EPFL',
 'Yale University',
 'The University of Edinburgh',
 'Tsinghua University',
 'Peking University',
 'Columbia University',
 'Princeton University',
 'Cornell University',
 'The University of Hong Kong',
 'The University of Tokyo',
 'University of Michigan-Ann Arbor',
 'Johns Hopkins University',
 'University of Toronto',
 'McGill University',
 'The Australian National University',
 'The University of Manchester',
 'Northwestern University',
 'Fudan University',
 'University of California, Berkeley (UCB)',
 'Kyoto University',
 'The Hong Kong University of Science and Technology',
 "King's College London",
 'Seoul National University',
 'The University of Melbourne',
 'The University of Sydney',
 'The Chinese University of Hong Kong (CUHK)',
 'University of California, Los Angeles (UCLA)',
 'KAIST - Korea Advanced Institute of Science & Technology',
 'New York University (NYU)',
 'The University of New South Wales (UNSW Sydney)',
 'Université PSL',
 'Zhejiang University',
 'University of British Columbia',
 'The University of Queensland',
 'University of California, San Diego (UCSD)',
 'Institut Polytechnique de Paris',
 'The London School of Economics and Political Science (LSE)',
 'Shanghai Jiao Tong University',
 'Technical University of Munich',
 'Duke University',
 'Carnegie Mellon University',
 'City University of Hong Kong',
 'University of Amsterdam',
 'Tokyo Institute of Technology (Tokyo Tech)',
 'Delft University of Technology',
 'Monash University',
 'Brown University',
 'The University of Warwick',
 'University of Bristol',
 'Ruprecht-Karls-Universität Heidelberg',
 'Ludwig-Maximilians-Universität München',
 'Universiti Malaya (UM)',
 'The Hong Kong Polytechnic University',
 'University of Texas at Austin',
 'National Taiwan University (NTU)',
 'Universidad de Buenos Aires (UBA)',
 'KU Leuven',
 'University of Zurich',
 'Sorbonne University',
 'University of Glasgow',
 'Korea University',
 'Osaka University',
 'University of Wisconsin-Madison',
 'University of Southampton',
 'Lomonosov Moscow State University',
 'University of Copenhagen',
 'Yonsei University',
 'Pohang University of Science And Technology (POSTECH)',
 'Durham University',
 'Tohoku University',
 'University of Illinois at Urbana-Champaign',
 'The University of Auckland',
 'University of Washington',
 'Universit Paris-Saclay',
 'Lund University',
 'Georgia Institute of Technology',
 'KTH Royal Institute of Technology ',
 'University of Birmingham',
 'University of St Andrews',
 'University of Leeds',
 'The University of Western Australia',
 'Rice University',
 'The University of Sheffield',
 'Pennsylvania State University',
 'Sungkyunkwan University (SKKU)',
 'University of Science and Technology of China',
 'Technical University of Denmark',
 'University of North Carolina, Chapel Hill',
 'Trinity College Dublin, The University of Dublin',
 'University of Oslo',
 'University of Nottingham',
 'University of Helsinki',
 'Universidad Nacional Autónoma de México  (UNAM)',
 'University of Geneva',
 'Washington University in St. Louis',
 'The University of Adelaide',
 'University of California, Davis',
 'King Abdulaziz University (KAU)',
 'Utrecht University',
 'Université de Montréal ',
 'Aalto University',
 'Boston University',
 'Leiden University',
 'University of Southern California',
 'Purdue University',
 'Queen Mary University of London',
 'Nagoya University',
 'University of Bern',
 'The Ohio State University',
 'Chalmers University of Technology',
 'Universidade de São Paulo',
 'Wageningen University & Research',
 'Uppsala University',
 'Eindhoven University of Technology',
 'University of Alberta',
 'Freie Universitaet Berlin',
 'Humboldt-Universität zu Berlin',
 'University of Groningen',
 'École Normale Supérieure de Lyon',
 'Nanjing University',
 'Lancaster University',
 'University of Technology Sydney',
 'Newcastle University',
 'Pontificia Universidad Católica de Chile (UC)',
 'KIT, Karlsruhe Institute of Technology',
 'Kyushu University',
 'University of Basel',
 'McMaster University',
 'Ghent University',
 'Politecnico di Milano',
 'Universiti Putra Malaysia (UPM)',
 'Universiti Kebangsaan Malaysia (UKM)',
 'Hokkaido University',
 'University of California, Santa Barbara (UCSB)',
 'Universiti Sains Malaysia (USM)',
 'Stockholm University',
 'The University of Exeter',
 'University of Waterloo',
 'Cardiff University',
 'University of Vienna',
 'University of York',
 'University of Rochester',
 'Aarhus University',
 'Hanyang University',
 'Michigan State University',
 'University of Maryland, College Park',
 'Technische Universität Berlin (TU Berlin)',
 'Emory University',
 'Case Western Reserve University',
 'Tecnológico de Monterrey',
 'King Fahd University of Petroleum & Minerals',
 'University of Pittsburgh',
 'RWTH Aachen University',
 'Alma Mater Studiorum - University of Bologna',
 'University of Bath',
 'Texas A&M University',
 'Universitat de Barcelona',
 'Western University',
 'Sapienza University of Rome',
 'Albert-Ludwigs-Universitaet Freiburg',
 'University College Dublin',
 'University of Florida',
 'Al-Farabi Kazakh National University',
 'University of Lausanne',
 'Eberhard Karls Universität Tübingen',
 'Indian Institute of Technology Bombay (IITB)',
 'Erasmus University Rotterdam ',
 'National Tsing Hua University',
 'Technische Universität Wien',
 'University of Gothenburg',
 'Khalifa University',
 'Universidad de Chile',
 'Indian Institute of Technology Delhi (IITD)',
 'Indian Institute of Science',
 'University of Minnesota Twin Cities',
 'Université catholique de Louvain (UCLouvain)',
 'University of Liverpool',
 'University of Twente',
 'Dartmouth College',
 'Universiti Teknologi Malaysia ',
 'University of Wollongong',
 'Curtin University',
 'Technische Universität Dresden',
 'University of Otago',
 'The University of Newcastle, Australia (UON)',
 'The Hebrew University of Jerusalem',
 'University of Bergen',
 'Macquarie University',
 'Keio University',
 'University of Reading',
 'Waseda University',
 'University of Göttingen',
 'University of Aberdeen',
 'RMIT University',
 'Universidad Autónoma de Madrid',
 'Universite libre de Bruxelles',
 'Universitat Autònoma de Barcelona',
 'Vrije Universiteit Amsterdam',
 'Tongji University',
 'Ulsan National Institute of Science and Technology (UNIST)',
 'Queensland University of Technology (QUT)',
 'Universität Hamburg',
 'Chulalongkorn University',
 'Arizona State University',
 "Queen's University Belfast",
 'Vanderbilt University',
 'Universidade Estadual de Campinas (Unicamp)',
 'Radboud University ',
 'Vrije Universiteit Brussel (VUB)',
 'University of Notre Dame',
 'Complutense University of Madrid',
 'Qatar University',
 'Wuhan University',
 'Rheinische Friedrich-Wilhelms-Universität Bonn',
 'University of Cape Town',
 'University of Sussex',
 'University of Virginia',
 'University of Ottawa',
 'Loughborough University',
 'University of California, Irvine',
 'Maastricht University ',
 'University of Antwerp',
 'University of Calgary',
 'Harbin Institute of Technology',
 'Universidad de los Andes',
 'University of Leicester',
 'Victoria University of Wellington',
 "Queen's University at Kingston",
 'USI - Università della Svizzera italiana',
 'American University of Beirut (AUB)',
 'Saint Petersburg State University',
 'Università di Padova',
 'Ecole des Ponts ParisTech',
 'Novosibirsk State University',
 'University of Massachusetts Amherst',
 'Georgetown University',
 'Universitat Pompeu Fabra (Barcelona)',
 'Universiti Brunei Darussalam (UBD)',
 'University of Colorado Boulder',
 'National Cheng Kung University (NCKU)',
 'Yeshiva University',
 'Gadjah Mada University',
 'Indian Institute of Technology Madras (IITM)',
 'Mahidol University',
 'Tel Aviv University',
 'National University of Ireland Galway',
 'Universidad Nacional de Colombia',
 'University of Canterbury | Te Whare Wānanga o Waitaha',
 'Sun Yat-sen University',
 'Sciences Po',
 'Université de Paris',
 'Kyung Hee University',
 'Rutgers University–New Brunswick',
 'Charles University',
 'University of Navarra',
 'National Yang Ming Chiao Tung University',
 'The University of Arizona',
 'Technical University of Darmstadt',
 'Beijing Normal University ',
 'Heriot-Watt University',
 'Dalhousie University',
 'Tomsk State University',
 'University of Surrey',
 'Southern University of Science and Technology',
 'Tufts University',
 'Graz University of Technology',
 'Indian Institute of Technology Kanpur (IITK)',
 'King Saud University',
 'Indian Institute of Technology Kharagpur (IIT-KGP)',
 'Bauman Moscow State Technical University',
 'Universität Innsbruck',
 'Deakin University',
 'Massey University',
 'University of Illinois at Chicago (UIC)',
 'University of Tsukuba',
 'Hong Kong Baptist University',
 'United Arab Emirates University',
 'Griffith University',
 'Moscow Institute of Physics and Technology (MIPT / Moscow Phystech)',
 'Universitas Indonesia',
 'Université Paris 1 Panthéon-Sorbonne ',
 'Xi’an Jiaotong University',
 'Belarusian State University',
 'University of Porto',
 'University of Turku',
 'Simon Fraser University',
 'University College Cork',
 'North Carolina State University',
 'University of Tartu',
 'University of Strathclyde',
 'Bandung Institute of Technology (ITB)',
 'University of Tasmania',
 'Gwangju Institute of Science and Technology (GIST)',
 'HSE University',
 'University of East Anglia (UEA)',
 'University of Warsaw ',
 'Jagiellonian University',
 'University of Southern Denmark (SDU)',
 'Indiana University Bloomington',
 'University of Cologne',
 'University of Miami',
 'National Taiwan University of Science and Technology (Taiwan Tech)',
 'Université Grenoble Alpes',
 'University of Milan',
 'IE University',
 'RUDN University',
 'National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)',
 'Universitat Politècnica de Catalunya · BarcelonaTech (UPC)',
 'Swinburne University of Technology',
 ' University of Dundee',
 'Friedrich-Alexander-Universität Erlangen-Nürnberg',
 'Pontificia Universidad Católica Argentina',
 'University of Macau',
 'Aalborg University',
 'University of South Australia',
 'L.N. Gumilyov Eurasian National University (ENU)',
 'Linköping University',
 'City, University of London',
 'Technion - Israel Institute of Technology',
 'Birkbeck, University of London',
 "Taylor's University",
 'Huazhong University of Science and Technology',
 'National Taiwan Normal University',
 'Politecnico di Torino',
 'Royal Holloway University of London',
 'Tianjin University',
 'University of Victoria (UVic)',
 'Goethe-University Frankfurt am Main',
 'University of Hawaiʻi at Mānoa',
 'Northeastern University',
 'Hiroshima University',
 'Universiti Teknologi Brunei',
 'Universität Jena',
 'Virginia Polytechnic Institute and State University',
 'Kazan (Volga region) Federal University',
 'UCSI University',
 'University of California, Santa Cruz',
 'Universität Stuttgart',
 'Brunel University London',
 'Universidad Carlos III de Madrid (UC3M)',
 'Ural Federal University - UrFU',
 'Johannes Kepler University Linz',
 'George Washington University',
 'Tilburg University',
 'University of Lisbon ',
 'Nankai University',
 'National University of Sciences And Technology (NUST) Islamabad',
 'University of Jyväskylä',
 'University of Utah',
 'Ewha Womans University',
 'La Trobe University',
 'MGIMO University',
 'ITMO University',
 'Umea University',
 'Ulm University',
 'Sultan Qaboos University',
 'Norwegian University of Science And Technology',
 'Universidade Federal do Rio de Janeiro',
 'Universitat Politècnica de València',
 'Lincoln University',
 'Beijing Institute of Technology',
 'University of Chemistry and Technology, Prague',
 'University of Connecticut',
 'University of Waikato',
 'University of Oulu',
 'Julius-Maximilians-Universität Würzburg',
 'Quaid-i-Azam University',
 'Stony Brook University, State University of New York',
 'Sharif University of Technology',
 'Tokyo Medical and Dental University (TMDU)',
 'American University of Sharjah',
 'Beihang University (former BUAA)',
 'University of Kent',
 'Kobe University',
 'University of Kansas',
 'University at Buffalo SUNY',
 'University of Pisa',
 'Università Vita-Salute San Raffaele',
 'SOAS University of London ',
 'Universidad de Palermo (UP)',
 'Peter the Great St. Petersburg Polytechnic University',
 'Ruhr-Universität Bochum',
 'Indian Institute of Technology Guwahati (IITG)',
 'National Research Tomsk Polytechnic University',
 'Pontificia Universidad Catolica del Peru',
 'Pakistan Institute of Engineering and Applied Sciences (PIEAS)',
 'University of the Philippines',
 'Indian Institute of Technology Roorkee (IITR)',
 'Universidad Austral',
 'Vilnius University ',
 'Czech Technical University in Prague',
 'Shandong University',
 'University of California, Riverside',
 'Flinders University',
 'South China University of Technology',
 'Taipei Medical University (TMU)',
 'Xiamen University',
 'Westfälische Wilhelms-Universität Münster ',
 'National Sun Yat-sen University',
 'Pontificia Universidad Javeriana',
 'Chung-Ang University (CAU)',
 'Lappeenranta-Lahti University of Technology LUT',
 'Tampere University',
 'Universiti Teknologi PETRONAS (UTP)',
 'University of Colorado, Denver ',
 'University of Science and Technology Beijing',
 'Université Laval',
 'National Technical University of Athens',
 'Université de Strasbourg',
 'Universität Mannheim',
 'James Cook University',
 'University of Naples - Federico II',
 'University of Witwatersrand',
 'Johannes Gutenberg Universität Mainz',
 'Washington State University',
 'Oxford Brookes University',
 'Wake Forest University',
 'Colorado State University',
 'Rensselaer Polytechnic Institute',
 'Universidade Nova de Lisboa',
 'Universidade Federal de São Paulo',
 'University of Johannesburg',
 'Shanghai University',
 'Tulane University',
 'University of Canberra ',
 'Essex, University of',
 'Swansea University',
 'University of Cyprus (UCY)',
 'University of Trento',
 'University of Tromsø The Arctic University of Norway',
 'Illinois Institute of Technology',
 'HUFS - Hankuk (Korea) University of Foreign Studies ',
 'The American University in Cairo',
 'Umm Al-Qura University ',
 'Universität  Leipzig',
 'Universität des Saarlandes',
 'University of Milano-Bicocca ',
 'Auckland University of Technology (AUT)',
 'Bond University',
 'Sichuan University',
 'University of Florence',
 'Brandeis University',
 'University of Coimbra',
 'University of Iowa',
 'University of Saskatchewan',
 'Universidad Politécnica de Madrid (UPM)',
 'University of St.Gallen (HSG)',
 'Colorado School of Mines',
 'Far Eastern Federal University',
 'Goldsmiths, University of London',
 'Martin-Luther-Universität Halle-Wittenberg',
 'Airlangga University',
 'Amirkabir University of Technology',
 'Southeast University',
 'Universidad de Belgrano',
 'National Taipei University of Technology',
 'Universidad de Montevideo (UM)',
 'Ben-Gurion University of The Negev',
 'Hasselt University ',
 'Universidad ORT Uruguay',
 'University of Stirling',
 'Florida State University',
 'University of Missouri, Columbia',
 'Bar-Ilan University',
 'Chiba University',
 'University of Texas Dallas',
 'Chang Gung University',
 'Université de Liège',
 'Auezov South Kazakhstan University (SKU)',
 'Stellenbosch University',
 'The Catholic University of Korea ',
 'Aston University',
 'University of Turin',
 'The National University of Science and Technology MISIS',
 'Universidad de Santiago de Chile (USACH)',
 'Yokohama City University',
 'Dublin City University',
 'Justus-Liebig-University Giessen',
 'UNESP',
 'University of Granada',
 ' Western Sydney University',
 'Boston College',
 'Christian-Albrechts-University zu Kiel',
 'Dongguk University ',
 'Iowa State University',
 'Sogang University',
 'University of Rome "Tor Vergata"',
 'York University',
 'Aix-Marseille University',
 'Jilin University',
 'Satbayev University',
 'Universidad de La Habana',
 'University of Bordeaux',
 'University of Delhi',
 'University of Klagenfurt',
 'University of Limerick',
 'Universität Konstanz',
 'Warsaw University of Technology',
 'Bogor Agricultural University',
 'Koç University',
 'Missouri University of Science and Technology',
 'Singapore Management University',
 'Universidad de Alcalá',
 'Universiti Utara Malaysia (UUM)',
 'University of Balamand',
 'V. N. Karazin Kharkiv National University',
 'Wayne State University',
 'Central South University',
 'China University of Geosciences',
 'Concordia University',
 'Imam Abdulrahman Bin Faisal University (IAU)',
 'National Central University',
 'Universidad Central "Marta Abreu" de Las Villas',
 'University of Bayreuth',
 'University of Eastern Finland',
 'University of Tehran',
 'Université de Montpellier',
 'Ajou University ',
 'East China Normal University',
 'Hitotsubashi University',
 'Institut National des Sciences Appliquées de Lyon (INSA)',
 'Lehigh University',
 'Nagasaki University',
 'National Research Saratov State University',
 'Oregon State University',
 'Saint Joseph University of Beirut (USJ) ',
 'Southern Federal University',
 'Universidad de Costa Rica',
 'Universidad de Zaragoza',
 'University of Delaware',
 'Aberystwyth University',
 'Iran University of Science and Technology',
 'Kyungpook National University',
 'Niigata University',
 'Northwestern Polytechnical University',
 'Sabanci University',
 'The University of Georgia',
 'The University of Tennessee, Knoxville',
 'University of Ulsan ',
 'Abai Kazakh National Pedagogical University',
 'Aristotle University of Thessaloniki',
 'Kazakh National Agrarian University KazNAU',
 'Masaryk University',
 'Middle East Technical University',
 'Universidad Panamericana (UP)',
 'Universidad de Sevilla',
 'University of Szeged',
 'Università Cattolica del Sacro Cuore',
 'Université Paul Sabatier Toulouse III',
 'Altai State University',
 'Hallym University ',
 'Inha University',
 'Jawaharlal Nehru University',
 'Technische Universität Braunschweig',
 'The New School',
 'Università degli Studi di Pavia',
 'Université de Fribourg',
 'Cairo University',
 'Dalian University of Technology',
 'East China University of Science and Technology',
 'Holy Spirit University of Kaslik ',
 'Hunan University ',
 'Ivane Javakhishvili Tbilisi State University',
 'Jeonbuk National University',
 'Osaka City University',
 'Universitat de Valencia',
 'University of Minho',
 'University of Nebraska - Lincoln',
 'Universität Bremen',
 'Lebanese American University',
 'Lingnan University, Hong Kong',
 'Murdoch University',
 'Okayama University',
 'Samara National Research University (Samara University)',
 'Universidad Nacional de La Plata (UNLP)',
 'University of Guelph',
 'University of South Florida',
 'Applied Science University - Bahrain',
 'Bilkent University',
 'Indian Institute of Technology Hyderabad',
 'Kumamoto University',
 'National Chengchi University',
 'Savitribai Phule Pune University',
 'Sofia University "St. Kliment Ohridski"',
 'Universidad Externado de Colombia ',
 'University of Debrecen',
 'University of Electronic Science and Technology of China',
 'University of Ljubljana',
 'Universität Regensburg',
 'Université du Québec',
 'Abo Akademi University',
 'American University in Dubai',
 'Ateneo de Manila University',
 'Bangor University',
 'Canadian University Dubai',
 'Carleton University',
 'Central Queensland University (CQUniversity Australia)',
 'Chiang Mai University',
 'China Agricultural University ',
 'Clark University',

In [ ]:
rank =[]
for i in range(len(sc)):
  rank.append(i+1)

In [ ]:
rank

In [ ]:
print(sc[501])
for i in range(502,len(sc)):
  sc[i]=0
print(sc)

 24.1
[' 100 ', ' 100 ', ' 99.5 ', ' 99.5 ', ' 98.7 ', ' 98.7 ', ' 98.7 ', ' 98.7 ', ' 98 ', ' 98 ', ' 93.9 ', ' 93.9 ', ' 90.8 ', ' 90.8 ', ' 90.7 ', ' 90.7 ', ' 90.2 ', ' 90.2 ', ' 90.2 ', ' 90.2 ', ' 88.3 ', ' 88.3 ', ' 86.3 ', ' 86.3 ', ' 86.2 ', ' 86.2 ', ' 86.2 ', ' 86.2 ', ' 85.9 ', ' 85.9 ', ' 82.6 ', ' 82.6 ', ' 82.5 ', ' 82.5 ', ' 82.3 ', ' 82.3 ', ' 82.2 ', ' 82.2 ', ' 82 ', ' 82 ', ' 79.1 ', ' 79.1 ', ' 78.9 ', ' 78.9 ', ' 77.7 ', ' 77.7 ', ' 77.6 ', ' 77.6 ', ' 77.4 ', ' 77.4 ', ' 75.6 ', ' 75.6 ', ' 75.6 ', ' 75.6 ', ' 75.2 ', ' 75.2 ', ' 74.6 ', ' 74.6 ', ' 74.6 ', ' 74.6 ', ' 71.2 ', ' 71.2 ', ' 71 ', ' 71 ', ' 70.8 ', ' 70.8 ', ' 70.1 ', ' 70.1 ', ' 69.8 ', ' 69.8 ', ' 67.2 ', ' 67.2 ', ' 67.1 ', ' 67.1 ', ' 66.8 ', ' 66.8 ', ' 66.3 ', ' 66.3 ', ' 66.2 ', ' 66.2 ', ' 65.4 ', ' 65.4 ', ' 65.2 ', ' 65.2 ', ' 65.2 ', ' 65.2 ', ' 65.2 ', ' 65.2 ', ' 65 ', ' 65 ', ' 62.9 ', ' 62.9 ', ' 62.8 ', ' 62.8 ', ' 62.6 ', ' 62.6 ', ' 62.5 ', ' 62.5 ', ' 62.3 ', ' 62.3 ', ' 59.6 ', ' 59.6 ', ' 59.5 ', ' 59.5 ', ' 59 ', ' 59 ', ' 58.9 ', ' 58.9 ', ' 58.5 ', ' 58.5 ', ' 57.7 ', ' 57.7 ', ' 57.5 ', ' 57.5 ', ' 57.3 ', ' 57.3 ', ' 57 ', ' 57 ', ' 57 ', ' 57 ', ' 56.1 ', ' 56.1 ', ' 56 ', ' 56 ', ' 55.9 ', ' 55.9 ', ' 55.9 ', ' 55.9 ', ' 55.8 ', ' 55.8 ', ' 54.8 ', ' 54.8 ', ' 54.6 ', ' 54.6 ', ' 54.2 ', ' 54.2 ', ' 54 ', ' 54 ', ' 53.9 ', ' 53.9 ', ' 52.7 ', ' 52.7 ', ' 52.6 ', ' 52.6 ', ' 52.5 ', ' 52.5 ', ' 52.2 ', ' 52.2 ', ' 52 ', ' 52 ', ' 50.5 ', ' 50.5 ', ' 50.4 ', ' 50.4 ', ' 50.4 ', ' 50.4 ', ' 50.4 ', ' 50.4 ', ' 50.3 ', ' 50.3 ', ' 48.6 ', ' 48.6 ', ' 48.2 ', ' 48.2 ', ' 48.2 ', ' 48.2 ', ' 48.1 ', ' 48.1 ', ' 48.1 ', ' 48.1 ', ' 47.5 ', ' 47.5 ', ' 47.2 ', ' 47.2 ', ' 47 ', ' 47 ', ' 46.9 ', ' 46.9 ', ' 46.9 ', ' 46.9 ', ' 46.1 ', ' 46.1 ', ' 46.1 ', ' 46.1 ', ' 46.1 ', ' 46.1 ', ' 46 ', ' 46 ', ' 46 ', ' 46 ', ' 45.5 ', ' 45.5 ', ' 45.1 ', ' 45.1 ', ' 45.1 ', ' 45.1 ', ' 44.9 ', ' 44.9 ', ' 44.8 ', ' 44.8 ', ' 44.1 ', ' 44.1 ', ' 43.9 ', ' 43.9 ', ' 43.5 ', ' 43.5 ', ' 43.3 ', ' 43.3 ', ' 43.2 ', ' 43.2 ', ' 42.6 ', ' 42.6 ', ' 42.5 ', ' 42.5 ', ' 42.4 ', ' 42.4 ', ' 42.1 ', ' 42.1 ', ' 42 ', ' 42 ', ' 41.1 ', ' 41.1 ', ' 41 ', ' 41 ', ' 40.9 ', ' 40.9 ', ' 40.8 ', ' 40.8 ', ' 40.7 ', ' 40.7 ', ' 40.2 ', ' 40.2 ', ' 40.1 ', ' 40.1 ', ' 40 ', ' 40 ', ' 39.8 ', ' 39.8 ', ' 39.8 ', ' 39.8 ', ' 39.5 ', ' 39.5 ', ' 39.5 ', ' 39.5 ', ' 39.2 ', ' 39.2 ', ' 39.2 ', ' 39.2 ', ' 39.2 ', ' 39.2 ', ' 38.6 ', ' 38.6 ', ' 38.5 ', ' 38.5 ', ' 38.4 ', ' 38.4 ', ' 38.4 ', ' 38.4 ', ' 38.3 ', ' 38.3 ', ' 37.7 ', ' 37.7 ', ' 37.4 ', ' 37.4 ', ' 37.3 ', ' 37.3 ', ' 37.3 ', ' 37.3 ', ' 37.2 ', ' 37.2 ', ' 36.9 ', ' 36.9 ', ' 36.7 ', ' 36.7 ', ' 36.7 ', ' 36.7 ', ' 36.6 ', ' 36.6 ', ' 36.6 ', ' 36.6 ', ' 36.4 ', ' 36.4 ', ' 36.3 ', ' 36.3 ', ' 36.2 ', ' 36.2 ', ' 36.2 ', ' 36.2 ', ' 36.1 ', ' 36.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 35.1 ', ' 34.7 ', ' 34.7 ', ' 34.7 ', ' 34.7 ', ' 34.4 ', ' 34.4 ', ' 34.2 ', ' 34.2 ', ' 34.2 ', ' 34.2 ', ' 33.8 ', ' 33.8 ', ' 33.7 ', ' 33.7 ', ' 33.7 ', ' 33.7 ', ' 33.7 ', ' 33.7 ', ' 33.6 ', ' 33.6 ', ' 33.1 ', ' 33.1 ', ' 33 ', ' 33 ', ' 32.9 ', ' 32.9 ', ' 32.9 ', ' 32.9 ', ' 32.9 ', ' 32.9 ', ' 32.4 ', ' 32.4 ', ' 32.4 ', ' 32.4 ', ' 32.3 ', ' 32.3 ', ' 32.3 ', ' 32.3 ', ' 32.2 ', ' 32.2 ', ' 32.1 ', ' 32.1 ', ' 32.1 ', ' 32.1 ', ' 31.9 ', ' 31.9 ', ' 31.8 ', ' 31.8 ', ' 31.7 ', ' 31.7 ', ' 31.4 ', ' 31.4 ', ' 31.3 ', ' 31.3 ', ' 31.3 ', ' 31.3 ', ' 31.3 ', ' 31.3 ', ' 31.2 ', ' 31.2 ', ' 30.9 ', ' 30.9 ', ' 30.9 ', ' 30.9 ', ' 30.8 ', ' 30.8 ', ' 30.8 ', ' 30.8 ', ' 30.8 ', ' 30.8 ', ' 30.3 ', ' 30.3 ', ' 30 ', ' 30 ', ' 29.8 ', ' 29.8 ', ' 29.6 ', ' 29.6 ', ' 29.6 ', ' 29.6 ', ' 29.4 ', ' 29.4 ', ' 29.3 ', ' 29.3 ', ' 29.3 ', ' 29.3 ', ' 29.1 ', ' 29.1 ', ' 29.1 ', ' 29.1 ', ' 28.6 ', ' 28.6 ', ' 28.5 ', ' 28.5 ', ' 28.5 ', ' 28.5 ', ' 28.4 ', ' 28.4 ', ' 28.4 ', ' 28.4 ', ' 28 ', ' 28 ', ' 28 ', ' 28 ', ' 28 ', ' 28 ', ' 27.9 ', ' 27.9 ', ' 27.9 ', ' 27.9 ', ' 27.7 ', ' 27.7 ', ' 27.5 ', ' 27.5 ', ' 27.5 ', ' 27.5 ', ' 27.4 ', ' 27.4 ', ' 27.4 ', ' 27.4 ', ' 27.3 ', ' 27.3 ', ' 27.3 ', ' 27.3 ', ' 27.2 ', ' 27.2 ', ' 27.1 ', ' 27.1 ', ' 27.1 ', ' 27.1 ', ' 26.8 ', ' 26.8 ', ' 26.8 ', ' 26.8 ', ' 26.8 ', ' 26.8 ', ' 26.7 ', ' 26.7 ', ' 26.7 ', ' 26.7 ', ' 26.3 ', ' 26.3 ', ' 26.3 ', ' 26.3 ', ' 26.3 ', ' 26.3 ', ' 26.2 ', ' 26.2 ', ' 26.1 ', ' 26.1 ', ' 25.8 ', ' 25.8 ', ' 25.8 ', ' 25.8 ', ' 25.8 ', ' 25.8 ', ' 25.8 ', ' 25.8 ', ' 25.7 ', ' 25.7 ', ' 25.4 ', ' 25.4 ', ' 25.4 ', ' 25.4 ', ' 25.4 ', ' 25.4 ', ' 25.4 ', ' 25.4 ', ' 25.3 ', ' 25.3 ', ' 25.1 ', ' 25.1 ', ' 25.1 ', ' 25.1 ', ' 25.1 ', ' 25.1 ', ' 25.1 ', ' 25.1 ', ' 25 ', ' 25 ', ' 24.7 ', ' 24.7 ', ' 24.6 ', ' 24.6 ', ' 24.6 ', ' 24.6 ', ' 24.6 ', ' 24.6 ', ' 24.5 ', ' 24.5 ', ' 24.3 ', ' 24.3 ', ' 24.2 ', ' 24.2 ', ' 24.2 ', ' 24.2 ', ' 24.1 ', ' 24.1 ', ' 24.1 ', ' 24.1 ', ' 24.1 ', ' 24.1 ', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
import re
for i in range(0,502):
   sc[i]= sc[i].replace(" ","")
sc

In [ ]:
import pandas as pd

dict = {'rank':rank,'university_name':data,'score':sc}
df = pd.DataFrame(dict)

In [ ]:
df['score']=df['score'].astype(float)
df['score']

0      100.0
1      100.0
2       99.5
3       99.5
4       98.7
       ...
995      0.0
996      0.0
997      0.0
998      0.0
999      0.0
Name: score, Length: 1000, dtype: float64

In [ ]:
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(x=df['rank'],y=df['score'])],
    layout_title_text="A Figure Displaying Itself"
)
fig

In [ ]:
df.to_csv("qs_Rankings.csv")

## Convert Scores from 0-100 scale to to 1-5

In [ ]:
# def convert(x,a,b,c=1,d=5):
#     """converts values in the range [a,b] to values in the range [c,d]"""
#     ans= round(c + float(x-a)*float(d-c)/(b-a))
#     if ans==0:
#       ans=1

#     return ans
# convert(91,20,100,1,5)

5

In [ ]:
new_scores =[]
def convert(x,a,b,c=1,d=5):
    """converts values in the range [a,b] to values in the range [c,d]"""
    ans= round(c + float(x-a)*float(d-c)/(b-a))
    if ans==0:
      ans=1

    return ans

for i in range(len(df['score'])):
  new_scores.append(convert(df['score'][i],20,100,1,5))

In [ ]:
new_scores

In [ ]:
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(x=df['rank'],y=new_scores)],
    layout_title_text="A Figure Displaying Itself"
)
fig

In [ ]:
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(x=new_scores,y=df['rank'])],
    layout_title_text="A Figure Displaying Itself"
)
fig

In [ ]:
df['University Rating']= new_scores

In [ ]:
df

     rank  ... University Rating
0       1  ...                 5
1       2  ...                 5
2       3  ...                 5
3       4  ...                 5
4       5  ...                 5
..    ...  ...               ...
995   996  ...                 1
996   997  ...                 1
997   998  ...                 1
998   999  ...                 1
999  1000  ...                 1

[1000 rows x 4 columns]

In [ ]:
df.to_csv("qs_Rankings.csv")

In [ ]:
! pip install -q kaggle

     |████████████████████████████████| 127 kB 5.3 MB/s
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
selenium 4.1.0 requires urllib3[secure]~=1.26, but you have urllib3 1.25.11 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.

In [ ]:
from google.colab import files
files.upload()

Saving kaggle (3).json to kaggle (3).json

{'kaggle (3).json': b'{"username":"adityam5153","key":"d37d960aa352ac9bdbf9a13d31470984"}'}

In [ ]:
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets list

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
ref                                                         title                                             size  lastUpdated          downloadCount
----------------------------------------------------------  -----------------------------------------------  -----  -------------------  -------------
prasertk/netflix-subscription-price-in-different-countries  Netflix subscription fee in different countries    3KB  2022-01-15 07:06:09           3008
nkitgupta/jigsaw-regression-based-data                      Jigsaw Regression Based Data                       3GB  2022-02-05 20:51:56            889
yasserh/wine-quality-dataset                                Wine Quality Dataset                              21KB  2022-01-15 19:15:11           2777
majyhain/height-of-male-and-female-by-country-2022          Height of Male and Female by Country 2022          4KB  2022-02-02 00:40:19            864
sanjeetsinghnaik/top-1000-highest-grossing-movies           Top 1000 Highest Grossing Movies                 106KB  2022-01-15 16:26:14           1922
yamqwe/air-traffic-passenger-datae                          🌁 Air Traffic Passenger Data                     173KB  2022-02-08 15:33:44            787
iamsouravbanerjee/analytics-industry-salaries-2022-india    Data Professionals Salary - 2022                  57KB  2022-02-04 09:04:46           3094
robikscube/ubiquant-parquet                                 Ubiquant Competition Data in Parquet Format       13GB  2022-01-19 14:18:59           1317
yamqwe/netflix-showse                                       Netflix Shows                                     11KB  2022-02-08 15:33:37           1659
georgesaavedra/covid19-dataset                              COVID-19 dataset                                   9MB  2022-02-11 16:14:49           1117
yamqwe/shark-tank-companiese                                📱 Shark Tank Companies                            70KB  2022-02-08 15:35:24            715
dansbecker/melbourne-housing-snapshot                       Melbourne Housing Snapshot                       451KB  2018-06-05 12:52:24          80489
datasnaek/youtube-new                                       Trending YouTube Video Statistics                201MB  2019-06-03 00:56:47         165528
maricinnamon/harry-potter-movies-dataset                    Harry Potter Movies Dataset                      211KB  2022-01-14 10:13:19            702
vivovinco/nba-player-stats                                  2021-2022 NBA Player Stats                        29KB  2022-01-22 14:53:22            747
kenjee/ken-jee-youtube-data                                 Ken Jee YouTube Data                               6MB  2022-01-22 20:38:53            206
zynicide/wine-reviews                                       Wine Reviews                                      51MB  2017-11-27 17:08:04         154049
residentmario/ramen-ratings                                 Ramen Ratings                                     40KB  2018-01-11 16:04:39          32412
datasnaek/chess                                             Chess Game Dataset (Lichess)                       3MB  2017-09-04 03:09:09          27584
rtatman/188-million-us-wildfires                            1.88 Million US Wildfires                        168MB  2020-05-12 21:03:49          18856

In [ ]:
! kaggle datasets download suneelpatel/graduate-admission-analysis-and-prediction

404 - Not Found

In [ ]:

! kaggle datasets download 'suneelpatel-graduate-admission-analysis-and-prediction'

404 - Not Found

In [ ]:
data = pd.read_csv('Admission_Predict.csv')

In [ ]:
data

     Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0             1        337          118  ...  9.65         1              0.92
1             2        324          107  ...  8.87         1              0.76
2             3        316          104  ...  8.00         1              0.72
3             4        322          110  ...  8.67         1              0.80
4             5        314          103  ...  8.21         0              0.65
..          ...        ...          ...  ...   ...       ...               ...
395         396        324          110  ...  9.04         1              0.82
396         397        325          107  ...  9.11         1              0.84
397         398        330          116  ...  9.45         1              0.91
398         399        312          103  ...  8.78         0              0.67
399         400        333          117  ...  9.66         1              0.95

[400 rows x 9 columns]

In [ ]:
df[df['rank']==21]

    rank     university_name  score  University Rating
20    21  Cornell University   88.3                  4

if rating 5 330 above and 110

In [ ]:
data[data['University Rating']==4]

     Serial No.  GRE Score  TOEFL Score  ...  CGPA  Research  Chance of Admit
0             1        337          118  ...  9.65         1              0.92
1             2        324          107  ...  8.87         1              0.76
11           12        327          111  ...  9.00         1              0.84
12           13        328          112  ...  9.10         1              0.78
21           22        325          114  ...  8.40         0              0.70
..          ...        ...          ...  ...   ...       ...               ...
384         385        340          113  ...  9.74         1              0.96
392         393        326          112  ...  9.12         1              0.84
394         395        329          111  ...  9.23         1              0.89
397         398        330          116  ...  9.45         1              0.91
399         400        333          117  ...  9.66         1              0.95

[74 rows x 9 columns]